spring:
  profiles:
    default: local

  # 공통
  data:
    mongodb:
      uri: ${DB_URI}
      auto-index-creation: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# 모니터링
management:
  endpoints:
    web:
      exposure:
        include: prometheus